global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'openfaas'
    static_configs:
      - targets: ['20.90.162.163:8080'] # OpenFaaS gateway public IP

  - job_name: 'prometheus'
    static_configs:
      - targets: ['20.90.162.163:9090'] # Prometheus itself

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['20.90.162.163:8081'] # cAdvisor metrics

  - job_name: 'docker'
    static_configs:
      - targets: ['20.90.162.163:9487'] # Docker metrics exporter

